# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-nhbs-dev"
    storage_account_name = "nhbstfstatestorage"
    container_name       = "tfstate"
    key                  = "dev/resource_group/terraform.tfstate"
  }
}
